# Copyright 2024 Proyectos y Sistemas de Mantenimiento SL (eProsima).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import rclpy
import re
import subprocess
import tempfile

from ament_index_python.packages import get_package_share_directory

from rcl_interfaces.msg import ParameterDescriptor, SetParametersResult
from rclpy.node import Node
from hri_msgs.msg import FaceInterface, Audio
from std_msgs.msg import Bool

from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy


def pick_control(card: int) -> str | None:
    """Return the name of a Simple mixer control for a given ALSA card, or None if not found."""
    PREFERRED_CONTROLS = [
        # Most common playback volume controls, in priority order
        "Master", "PCM", "Speaker", "Headphone", "Headset", "Line Out", "Front",
        "Digital", "HDMI", "IEC958"
    ]
    controls = list_simple_controls(card)
    for name in PREFERRED_CONTROLS:
        if name in controls and control_has_playback_volume(card, name):
            return name
    return None


def list_simple_controls(card: int) -> list[str]:
    """Return a list of Simple mixer control names for a given ALSA card."""
    p = subprocess.run(["amixer", "-c", str(card), "scontrols"], capture_output=True, text=True, check=True)
    names: list[str] = []
    for line in p.stdout.splitlines():
        # Example: "Simple mixer control 'Master',0"
        m = re.search(r"Simple mixer control '([^']+)'", line)
        if m:
            names.append(m.group(1))
    return names


def control_has_playback_volume(card: int, control: str) -> bool:
    """Check if a control has Playback volume capability (pvolume) via `amixer get`."""
    p = subprocess.run(["amixer", "-c", str(card), "get", control], capture_output=True, text=True, check=True)
    # Look for capabilities line or 'Playback' lines
    if "Capabilities:" in p.stdout:
        caps_line = ""
        for line in p.stdout.splitlines():
            if "Capabilities:" in line:
                caps_line = line
                break
        if "pvolume" in caps_line:
            return True
    # Fallback heuristic: look for "Playback" lines with percentage
    if re.search(r"Playback.*\[\d+%\]", p.stdout):
        return True
    return False


class TTSSub(Node):
    """
    Node that provides a TTS subscriber from an Audio topic (raw bytes + metadata) and plays the audio.
    The purpose of this node is to play the messages generated by the TTSPub, exemplifying a potential integration into
    the TTS system.
    It requires to have access to a speaker device.
    """

    def __init__(self):
        super().__init__('hri_tts_sub')

        # Speaker model
        self.declare_parameter(
            'card_number', -1, ParameterDescriptor(
                description='Card number used by aplay to find the sound card device in the system.'))
        self.declare_parameter(
            'device_index', 0, ParameterDescriptor(
                description='Device index used by aplay to find the device in the system if there are multiple.'))
        self.declare_parameter(
            'volume', 70, ParameterDescriptor(
                description='Volume level (%)'))
        self.declare_parameter(
            'publish_face_expression', True, ParameterDescriptor(
                description='If the node should publish the face expression when speaking.')
        )

        self.card_number = self.get_parameter('card_number').value
        self.device_idx = self.get_parameter('device_index').value
        if self.card_number == -1:
            self.get_logger().error("Card number parameter is empty. Please set the card number parameter.")
            raise ValueError("Card number parameter is empty. Please set the card number parameter.")
        self.volume = str(self.get_parameter('volume').value)+'%'
        # Add callback to update parameters (volume only) at runtime
        self.param_change_callback = self.add_on_set_parameters_callback(self.parameter_callback)
        self.should_pub_face_expression = self.get_parameter('publish_face_expression').value

        # Path on destination computer for audio_files
        package_share_directory = get_package_share_directory('hri_tts')
        self.audio_files_path = os.path.join(package_share_directory, 'audio_files')
        # Check if the directory exists to avoid runtime exceptions
        if not os.path.exists(self.audio_files_path):
            self.get_logger().error(f"Audio directory not found: {self.audio_files_path}")
            raise FileNotFoundError(f"Audio directory not found: {self.audio_files_path}")
        else:
            self.get_logger().info(f"Audio directory found: {self.audio_files_path}")

        self.last_id = 0

        # QoS Configuration
        qos_1_reliable = QoSProfile(
            reliability=ReliabilityPolicy.RELIABLE,
            history=HistoryPolicy.KEEP_LAST,
            depth=5  # This queue controls the number of sentences that can be stored
        )

        # Create a subscriber to the /hri_tts/audio topic
        self.subscription = self.create_subscription(
            Audio,
            '/hri_tts/audio',
            self.tts_callback,
            qos_1_reliable
        )

        # Create a publisher to the /hri_tts/finished topic
        self.publisher_finished = self.create_publisher(Bool, '/hri_tts/finished', qos_1_reliable)

        # Create a publisher to the /face_expression topic to interact with the face expression node
        if self.should_pub_face_expression:
            self.publisher_face_exp = self.create_publisher(FaceInterface, '/face_expression', qos_1_reliable)

        # Find which sound card is the one with the actual speaker
        self.card_device = f'plughw:{self.card_number},{self.device_idx}' if self.card_number is not None else 'plughw:0,0'
        self.volume_control = None
        # Establish the volume
        try:
            self.volume_control = pick_control(self.card_number) if self.card_number is not None else None
            if self.volume_control is not None:
                subprocess.run(['amixer', '-c', str(self.card_number), 'set', str(self.volume_control), self.volume], check=True)
        except Exception as e:
            self.get_logger().error(f"Error setting volume: {e}")

    def play_audio_file(self, input_file, speed=1.25):
        """ Play an audio file with a specific playback speed. """
        # Use ffmpeg to change the playback speed without changing the pitch
        temp_file = tempfile.NamedTemporaryFile(delete=True, suffix=f'.wav')
        command = [
            "ffmpeg", "-i", input_file, "-filter:a", f"atempo={speed}",
            "-vn", temp_file.name, "-y", "-loglevel", "quiet"
        ]
        try:
            subprocess.run(command)
        except Exception as e:
            self.get_logger().error(f"Error adjusting audio speed: {e}")
            return
        # Play the audio
        try:
            subprocess.run(['aplay', '-D', self.card_device, temp_file.name, "-q"], check=True)
        except Exception as e:
            self.get_logger().error(f"Error playing audio: {e}")

    def play_audio_msg(self, msg, speed=1.25):
        """ Play an audio message with a specific playback speed. """
        # Create the file to play
        temp_file = tempfile.NamedTemporaryFile(delete=True, suffix=f'.{msg.subtype}')
        audio_bytes = b''.join(msg.data)
        temp_file.write(audio_bytes)
        temp_file.flush()
        # Use ffmpeg to change the playback speed without changing the pitch
        temp_adjusted = tempfile.NamedTemporaryFile(delete=True, suffix=f'.{msg.subtype}')
        command = [
            "ffmpeg", "-i", temp_file.name, "-filter:a", f"atempo={speed}",
            "-vn", temp_adjusted.name, "-y", "-loglevel", "quiet"
        ]
        try:
            subprocess.run(command)
            play_file_name = temp_adjusted.name
        except Exception as e:
            self.get_logger().error(f"Error adjusting audio speed: {e}")
            play_file_name = temp_file.name
        # Play the audio
        try:
            subprocess.run(['aplay', '-D', self.card_device, play_file_name, "-q"], check=True)
        except Exception as e:
            self.get_logger().error(f"Error playing audio: {e}")

    def tts_callback(self, msg):
        """ Callback function for the /hri_tts/audio topic that plays either a preset audio or an Audio msg. """
        try:
            if self.last_id != 0 and self.last_id != (msg.id - 1):
                self.get_logger().error(f"Received audio {msg.id} out of order, expected {self.last_id + 1}")
            # Play preset if specified
            if msg.preset != 0:
                self.play_preset(msg.preset)
                return

            # Play audio received in the message
            self.last_id = msg.id
            self.get_logger().info(f"Playing audio {msg.id} of {msg.sentences} sentences")
            # Publish a SPEAKING message to the /face_expression topic
            self.publish_face_expression('speaking')
            self.play_audio_msg(msg)
        finally:
            # Publish a NEUTRAL message to the /face_expression topic
            self.publish_face_expression('neutral')
            if msg.id == msg.sentences and msg.preset == 0:
                # Publish a True message to the /hri_tts/finished topic
                self.last_id = 0
                self.get_logger().info(f"Publishing end of audio {msg.id}/{msg.sentences}")
                self.publisher_finished.publish(Bool(data=True))

    def play_preset(self, preset):
        """ Play a preset audio file. These files are installed in the audio_files directory. """
        # Publish a SPEAKING or DANCING message to the /face_expression topic
        speed = 1.25
        if (preset == 105):
            self.publish_face_expression('dancing')
            speed = 1.0
        else:
            self.publish_face_expression('speaking')
        self.play_audio_file(f'{self.audio_files_path}/{preset}.wav', speed)
        # Publish a True message to the /hri_tts/finished topic
        self.get_logger().info(f"Publishing end of sentence of preset {preset}")
        self.publisher_finished.publish(Bool(data=True))
        # Publish a NEUTRAL message to the /face_expression topic
        self.publish_face_expression('neutral')

    def publish_face_expression(self, expression: str):
        """ Publish a face expression. """
        if self.should_pub_face_expression:
            face_msg = FaceInterface()
            if expression == 'speaking':
                face_msg.face = FaceInterface.SPEAKING
            elif expression == 'dancing':
                face_msg.face = FaceInterface.DANCING
            else:
                face_msg.face = FaceInterface.NEUTRAL
            self.publisher_face_exp.publish(face_msg)

    def parameter_callback(self, params):
        """Callback to update parameters."""
        result = SetParametersResult()
        result.successful = False
        for param in params:
            if param.name == 'volume':
                self.volume = str(param.value)+'%'
                try:
                    subprocess.run(['amixer', '-c', str(self.card_number), 'set', str(self.volume_control), self.volume], check=True)
                    result.successful = True
                except Exception as e:
                    self.get_logger().error(f"Error setting volume to {self.volume}: {e}")
            else:
                self.get_logger().error(f"Parameter '{param.name}' cannot be changed at runtime.")
        return result


def main(args=None):
    rclpy.init(args=args)

    try:
        tts_sub = TTSSub()
    except Exception as e:
        rclpy.logging.get_logger("NodeTTS").error(f"Failed to create NodeTTS: {e}")
        return

    try:
        rclpy.spin(tts_sub)
    except KeyboardInterrupt:
        # Handle Ctrl+C
        print("Shutting down node (Ctrl+C pressed).")
    finally:
        # rclpy.shutdown() is already being called in the destructor of the Node
        print("TTS subscriber node shutdown")
        # Destroy the node explicitly
        tts_sub.destroy_node()


if __name__ == '__main__':
    main()
