<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hri_tts</name>
  <version>1.0.0</version>
  <description>ROS 2 Action server implementing Text to Speech features</description>
  <author email="eugeniocollado@eprosima.com">Eugenio Collado</author>
  <maintainer email="carlosferreira@eprosima.com">Carlos Ferreira</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>hri_msgs</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
